<option value="Amity School Of Engineering, Noida."> </option>
<option value="Amrita University, Coimbatore">Amrita University, Coimbatore</option>
<option value="B.I.T, Bhilai.">B.I.T, Bhilai. </option>
<option value="B.I.T. Mesra, Ranchi.">B.I.T. Mesra, Ranchi. </option>
<option value="B.I.T. Sindri.">B.I.T. Sindri. </option>
<option value="BITS Pilani Goa Campus.">BITS Pilani Goa Campus. </option>
<option value="Bengal Engineering And Science University,Shibpur.">Bengal Engineering And Science University,Shibpur. </option>
<option value="CBIT, Hydrabad">CBIT, Hydrabad</option>
<option value="College Of Engineering(C,E.G.),Anna.">College Of Engineering(C,E.G.),Anna. </option>
<option value="Dayanand Sagar College Of Engineering,Bangalore. ">Dayanand Sagar College Of Engineering,Bangalore. </option>
<option value="Delhi College Of Engineering.">Delhi College Of Engineering. </option>
<option value="Dhaneswar Rath Institute Of Engineering And Management Studies, Cuttak.">Dhaneswar Rath Institute Of Engineering And Management Studies, Cuttak. </option>
<option value="Dinabandhu Andrews Institute Of Technology And Management, Kolkata.">Dinabandhu Andrews Institute Of Technology And Management, Kolkata. </option>
<option value="Dr. B. C. ROY Engg. College, Durgapur.">Dr. B. C. ROY Engg. College, Durgapur. </option>
<option value="Dr.GHS Institute Of Management & Research,Kanpur.">Dr.GHS Institute Of Management & Research,Kanpur. </option>
<option value="East West Institute Of Technology, Bangalore. ">East West Institute Of Technology, Bangalore. </option>
<option value="Eastern Academy Of Science & Technology,Bhubaneswar. ">Eastern Academy Of Science & Technology,Bhubaneswar. </option>
<option value="FMS, Delhi.">FMS, Delhi. </option>
<option value="Faculty Of Engineering & Technology,Raja Balwant Singh College, Agra. ">Faculty Of Engineering & Technology,Raja Balwant Singh College, Agra. </option>
<option value="Faculty Of Engineering And Technology,Agra College. ">Faculty Of Engineering And Technology,Agra College. </option>
<option value="Farah College Of Engineering And Technology, Hyderabad. ">Farah College Of Engineering And Technology, Hyderabad. </option>
<option value="Future Institute Of Engineering And Management(FIEM), Kolkata.">Future Institute Of Engineering And Management(FIEM), Kolkata. </option>
<option value="G.L.A Institute Of Technology And Management, Mathura. ">G.L.A Institute Of Technology And Management, Mathura. </option>
<option value="G.Narayanamma Institute Of Technology And Science, Hyderabad. ">G.Narayanamma Institute Of Technology And Science, Hyderabad. </option>
<option value="Gandhi Institute Of Technology And Management, Visakapatnam.">Gandhi Institute Of Technology And Management, Visakapatnam. </option>
<option value="Gayatri Vidya Parishad College Of Engineering, Visakhapatnam.">Gayatri Vidya Parishad College Of Engineering, Visakhapatnam. </option>
<option value="Ghanashyam Hemalata Institute Of Technology And Management(GHITM), Puri. ">Ghanashyam Hemalata Institute Of Technology And Management(GHITM), Puri. </option>
<option value="Goa Institute Of Management, Goa">Goa Institute Of Management, Goa </option>
<option value="Great Lakes Institute Of Management, Chennai">Great Lakes Institute Of Management, Chennai </option>
<option value="HMS Polytechnic, Tumkur. ">HMS Polytechnic, Tumkur. </option>
<option value="Haldia Institute Of Technology, Kolkata.">Haldia Institute Of Technology, Kolkata. </option>
<option value="Heramba Chandra College, Kolkata.">Heramba Chandra College, Kolkata. </option>
<option value="Heritage Institute Of Technology, Kolkata. ">Heritage Institute Of Technology, Kolkata. </option>
<option value="Hooghly Engineering & Technology College.">Hooghly Engineering & Technology College. </option>
<option value="IET DAVV, Indore. ">IET DAVV, Indore. </option>
<option value="IIIT Hyderabad.">IIIT Hyderabad. </option>
<option value="IIIT Kolkata.">IIIT Kolkata. </option>
<option value="IIM Ahmedabad.">IIM Ahmedabad. </option>
<option value="IIM Bangalore.">IIM Bangalore. </option>
<option value="IIM Indore.">IIM Indore. </option>
<option value="IIM Kolkata.">IIM Kolkata. </option>
<option value="IIM Kozhikode.">IIM Kozhikode. </option>
<option value="IIM Lucknow.">IIM Lucknow. </option>
<option value="IIT Bombay.">IIT Bombay. </option>
<option value="IIT Chennai.">IIT Chennai. </option>
<option value="IIT Delhi.">IIT Delhi. </option>
<option value="IIT Guwahati.">IIT Guwahati. </option>
<option value="IIT Kanpur.">IIT Kanpur. </option>
<option value="IIT Kharagpur.">IIT Kharagpur. </option>
<option value="IIT Roorkee.">IIT Roorkee. </option>
<option value="Indian Institute Of Foreign Trade, Delhi">Indian Institute Of Foreign Trade, Delhi </option>
<option value="Indian Institute Of Foreign Trade, Kolkata">Indian Institute Of Foreign Trade, Kolkata </option>
<option value="Indian School Of Business, Hyderabad">Indian School Of Business, Hyderabad </option>
<option value="Indian School Of Mines , Dhanbad.">Indian School Of Mines , Dhanbad. </option>
<option value="Indira Gandhi Engineering College, Sagar.">Indira Gandhi Engineering College , Sagar. </option>
<option value="Indira Gandhi Institute Of Technology, Dhenkanal. ">Indira Gandhi Institute Of Technology, Dhenkanal.</option>
<option value="Institute Of Chartered Financial Analysts Of India, Hyderabad">Institute Of Chartered Financial Analysts Of India, Hyderabad </option>
<option value="Institute Of Engineering & Management, Kolkata.">Institute Of Engineering &amp; Management, Kolkata. </option>
<option value="Institute Of Engineering & Rural Technology(IERT), Allahabad.">Institute Of Engineering &amp; Rural Technology(IERT), Allahabad.</option>
<option value="Institute Of Engineering, Thapathali Campus, Kathmandu.">Institute Of Engineering, Thapathali Campus, Kathmandu.</option>
<option value="Institute Of Management Studies, Indore">Institute Of Management Studies, Indore </option>
<option value="Institute Of Management Technology, Ghaziabad">Institute Of Management Technology, Ghaziabad </option>
<option value="Institute Of Management Technology, Nagpur">Institute Of Management Technology, Nagpur </option>
<option value="Institute Of Management Technology, Gaziabad.">Institute Of Management Technology, Gaziabad. </option>
<option value="Institute Of Rural Management, Anandd">Institute Of Rural Management, Anandd </option>
<option value="Institute Of Technical Education And Research, Bhubaneswar. ">Institute Of Technical Education And Research, Bhubaneswar. </option>
<option value="Institute Of Technology & Marine Engineering. ">Institute Of Technology &amp; Marine Engineering. </option>
<option value="International Institute Of Information Technology, Bangalore. ">International Institute Of Information Technology, Bangalore. </option>
<option value="J.B.Institute Of Engineering & Technology,Hyderabad. ">J.B.Institute Of Engineering &amp; Technology,Hyderabad. </option>
<option value="JBIMS, Mumbai.">JBIMS,Mumbai. </option>
<option value="JIS College Of Engineering, Kalyani.">JIS College Of Engineering,Kalyani.</option>
<option value="JSS Academy Of Technical Education, Noida.">JSS Academy Of Technical Education, Noida.</option>
<option value="Jadavpur University, Kolkata.">Jadavpur University, Kolkata. </option>
<option value="Jamnalal Bajaj Institute Of Management Studies, Mumbai">Jamnalal Bajaj Institute Of Management Studies, Mumbai </option>
<option value="Jawaharlal Nehru Technological University, Hyderabad.">Jawaharlal Nehru Technological University, Hyderabad.</option>
<option value="Jaypee Institute Of Information Technology, Noida.">Jaypee Institute Of Information Technology, Noida.</option>
<option value="Jyothi Engineering College, Medak(AP).">Jyothi Engineering College, Medak(AP).</option>
<option value="Kalasalingam University, Krishnankovil">Kalasalingam University, Krishnankovil</option>
<option value="K.I.S.D,Bhubaneshwar.">K.I.S.D,Bhubaneshwar.</option>
<option value="KEC College Of Education, Tiruvannamalai(TN).">KEC College Of Education, Tiruvannamalai(TN). </option>
<option value="KEWAL BAGDE">KEWAL BAGDE </option>
<option value="KJ Somaiya, Mumbai">KJ Somaiya, Mumbai </option>
<option value="Kalinga Institute Of Industrial Technology,Bhubaneswar">Kalinga Institute Of Industrial Technology,Bhubaneswar </option>
<option value="Kavikulguru Institute Of Technology & Science(WTS), Nagpur.">Kavikulguru Institute Of Technology & Science(WTS), Nagpur. </option>
<option value="Konark Institute Of Science And Technology, Bhubaneshwar.">Konark Institute Of Science And Technology, Bhubaneshwar. </option>
<option value="Koneru Lakshmaiah College Of Engineering, Guntur(AP).">Koneru Lakshmaiah College Of Engineering, Guntur(AP). </option>
<option value="Krupajal Engineering College, Bhubaneshwar.">Krupajal Engineering College, Bhubaneshwar. </option>
<option value="LIT, Nagpur.">LIT, Nagpur. </option>
<option value="Laksmni Narain College Of Technology,Bhopal.">Laksmni Narain College Of Technology,Bhopal. </option>
<option value="M.E.R.I., Kolkata.">M.E.R.I., Kolkata. </option>
<option value="M.G.1.T,Hyderabad.">M.G.1.T,Hyderabad. </option>
<option value="MCKVIE, Kolkata.">MCKVIE, Kolkata. </option>
<option value="MES College Of Engineering, Kuttippuram.">MES College Of Engineering, Kuttippuram. </option>
<option value="MJ College Of Engineering & Technology, Hyderabad.">MJ College Of Engineering & Technology, Hyderabad. </option>
<option value="MP Christian College Of Engineering And Technology, Bhilai.">MP Christian College Of Engineering And Technology, Bhilai. </option>
<option value="MVSR Engineering College, Ranga Reddy(AP).">MVSR Engineering College, Ranga Reddy(AP). </option>
<option value="Madan Mohan Malaviya Engineering College,Gorakhpur.">Madan Mohan Malaviya Engineering College,Gorakhpur. </option>
<option value="Maharaj Vijayaram Gajapathi Raj College Of Engineering, Vizianagaram.">Maharaj Vijayaram Gajapathi Raj College Of Engineering, Vizianagaram. </option>
<option value="Maharaja Agrasen Institute Of Technology, Delhi.">Maharaja Agrasen Institute Of Technology, Delhi. </option>
<option value="Malaviya National Institute Of Technology(MNIT), Jaipur.">Malaviya National Institute Of Technology(MNIT), Jaipur. </option>
<option value="Management Development Institute, Gurgaon">Management Development Institute, Gurgaon </option>
<option value="Manipal Institute Of Technology Sikkim.">Manipal Institute Of Technology Sikkim. </option>
<option value="Maulana Azad National Institute Of Technology, Bhopal.">Maulana Azad National Institute Of Technology, Bhopal. </option>
<option value="Meghnad Saha Institute Of Technology, Kolkata">Meghnad Saha Institute Of Technology, Kolkata </option>
<option value="Modern Education Society College Of Engineering, Pune.">Modern Education Society College Of Engineering, Pune. </option>
<option value="Mudra Institute Of Communications, Ahmedabad">Mudra Institute Of Communications, Ahmedabad </option>
<option value="N.I.T Jalandhar.">N.I.T Jalandhar. </option>
<option value="N.I.T Kurukshetra.">N.I.T Kurukshetra. </option>
<option value="N.I.T Patna.">N.I.T Patna. </option>
<option value="N.I.T Raipur.">N.I.T Raipur. </option>
<option value="N.I.T Rourkela.">N.I.T Rourkela. </option>
<option value="N.I.T Warangal.">N.I.T Warangal. </option>
<option value="N.I.T. Durgapur.">N.I.T. Durgapur. </option>
<option value="N.I.T. Jamshedpur.">N.I.T. Jamshedpur. </option>
<option value="N.I.T. Tiruchchirappalli.">N.I.T. Tiruchchirappalli. </option>
<option value="N.I.T.K Surathkal.">N.I.T.K Surathkal. </option>
<option value="NIRMA, Ahmedabad">NIRMA, Ahmedabad </option>
<option value="NRI Institute Of Information Science & Technology(NIIST), Bhopal.">NRI Institute Of Information Science & Technology(NIIST), Bhopal. </option>
<option value="Narayana Engineering College, Nellore(AP).">Narayana Engineering College, Nellore(AP). </option>
<option value="Narsee Munjee Insititute Of Management Studies, Mumbai">Narsee Munjee Insititute Of Management Studies, Mumbai </option>
<option value="Narula Institute Of Technology, Kolkata.">Narula Institute Of Technology, Kolkata. </option>
<option value="National Institute Of Aeronautical Engineering, Dehradun.">National Institute Of Aeronautical Engineering, Dehradun. </option>
<option value="National Institute Of Foundry And Forge Technology, Ranchi.">National Institute Of Foundry And Forge Technology, Ranchi. </option>
<option value="National Institute Of Industria Engineering, Mumbai">National Institute Of Industria Engineering, Mumbai </option>
<option value="National Institute Of Science And Technology(NIST), Berhampur.">National Institute Of Science And Technology(NIST), Berhampur. </option>
<option value="Netaji Subash Institute Of Technology, Delhi.">Netaji Subash Institute Of Technology, Delhi. </option>
<option value="Netaji Subhash Engineering College, Kolkata.">Netaji Subhash Engineering College, Kolkata. </option>
<option value="New Government College, Raipur.">New Government College, Raipur. </option>
<option value="Oriental Institute Of Science And Technology, Bhopal.">Oriental Institute Of Science And Technology, Bhopal. </option>
<option value="Osmania University College Of Engineering, Hyderabad.">Osmania University College Of Engineering, Hyderabad. </option>
<option value="P,V. P.1.T. Budhgaon, Sangli. ">P,V. P.1.T. Budhgaon, Sangli. </option>
<option value="P.R.R.M Engineering College, Ranga Reddy(AP).">P.R.R.M Engineering College, Ranga Reddy(AP). </option>
<option value="PES Institute Of Technology, Bangalore">PES Institute Of Technology, Bangalore </option>
<option value="PIET College Of Engineering, Pune.">PIET College Of Engineering, Pune. </option>
<option value="PIRM Engineering College, Chevella. ">PIRM Engineering College, Chevella. </option>
<option value="PVP Siddhartha Institute Of Technology, Vijayawada. ">PVP Siddhartha Institute Of Technology, Vijayawada. </option>
<option value="Poornima College, Jaipur. ">Poornima College, Jaipur. </option>
<option value="Pragati Engineering College, Kakinada(AP). ">Pragati Engineering College, Kakinada(AP). </option>
<option value="Princeton College Of Engineering & Technology. ">Princeton College Of Engineering & Technology. </option>
<option value="Punjab Engineering College.">Punjab Engineering College. </option>
<option value="Pydah College Of Engineering And Technology, Boyapalem. ">Pydah College Of Engineering And Technology, Boyapalem. </option>
<option value="R.V.S College Of Engineering And Technology, Bangalore.">R.V.S College Of Engineering And Technology, Bangalore. </option>
<option value="RKDF Institute Of Science & Technology, Bhopal. ">RKDF Institute Of Science & Technology, Bhopal. </option>
<option value="Raghu Engineering College, Visakhapatnam. ">Raghu Engineering College, Visakhapatnam. </option>
<option value="Rungta College Of Engineering & Technology, Bhilai. ">Rungta College Of Engineering & Technology, Bhilai. </option>
<option value="S.G.S.I.T.S, Indore. ">S.G.S.I.T.S, Indore. </option>
<option value="SASTRA University, Thanjavur.">SASTRA University, Thanjavur. </option>
<option value="SATHYABAMA University, Chennai">SATHYABAMA University, Chennai</option>
<option value="SCMHRD, Pune">SCMHRD, Pune </option>
<option value="SOE Cusat, Kochi. ">SOE Cusat, Kochi. </option>
<option value="SP Jain Institute Of Mangement And Research,Mumbai.">SP Jain Institute Of Mangement And Research,Mumbai. </option>
<option value="SRKNEC, Nagpur. ">SRKNEC, Nagpur. </option>
<option value="SRM Institute Of Technology,Chennai.">SRM Institute Of Technology,Chennai. </option>
<option value="Sagar Institute Of Research And Technology, Bhopal. ">Sagar Institute Of Research And Technology, Bhopal. </option>
<option value="Samrat Ashok Technological Institute,Vidisha. ">Samrat Ashok Technological Institute,Vidisha. </option>
<option value="Sant Samarth Engineering College -Bandlaguda, Hyderabad. ">Sant Samarth Engineering College -Bandlaguda, Hyderabad. </option>
<option value="Saptagiri College,Mangalore. ">Saptagiri College,Mangalore. </option>
<option value="Sardar Vallabhai National Institute Of Technology, Surat. ">Sardar Vallabhai National Institute Of Technology, Surat. </option>
<option value="Sardar Vallabhbhai Patel Institute Of Technology (SVIT), Vasad.">Sardar Vallabhbhai Patel Institute Of Technology (SVIT), Vasad. </option>
<option value="Shaheed Bhagat Singh College Of Engineering And Technology, Ferozpur. ">Shaheed Bhagat Singh College Of Engineering And Technology, Ferozpur. </option>
<option value="Shivdan Singh Institute Of Technology And Management, Aligarh.">Shivdan Singh Institute Of Technology And Management, Aligarh. </option>
<option value="Shree Shankaracharya College Of Engineering And Technology, Bhilai. ">Shree Shankaracharya College Of Engineering And Technology, Bhilai. </option>
<option value="Siddaganga Institute Of Technology,Bangalore. ">Siddaganga Institute Of Technology,Bangalore. </option>
<option value="Silicon Institute Of Technology, Bhubaneswar. ">Silicon Institute Of Technology, Bhubaneswar. </option>
<option value="Sinhgad College Of Engineering, Pune. ">Sinhgad College Of Engineering, Pune. </option>
<option value="Sreenidhi Institute Of Science And Technology (SNIST), Hyderabad. ">Sreenidhi Institute Of Science And Technology (SNIST), Hyderabad. </option>
<option value="Sri Indu College Of Engineering And Technology, Ranga Reddy(AP). ">Sri Indu College Of Engineering And Technology, Ranga Reddy(AP). </option>
<option value="Sri Muthukumaran Institute Of Technology(SMIT), Chennai. ">Sri Muthukumaran Institute Of Technology(SMIT), Chennai. </option>
<option value="Sri Sai Ram Engineering College, Chennai. ">Sri Sai Ram Engineering College, Chennai. </option>
<option value="Sridevi Women Engineering College, Hyderabad. ">Sridevi Women Engineering College, Hyderabad. </option>
<option value="S S N College of Engineering, Chennai. ">S S N College of Engineering, Chennai. </option>
<option value="St Sthephens College, Delhi.">St Sthephens College, Delhi. </option>
<option value="St. Peters Engineering College, Chennai.">St. Peters Engineering College, Chennai. </option>
<option value="St.Marys College Of Engineering.">St.Mary's College Of Engineering. </option>
<option value="St.Joseph College Of Engineering.">St.Joseph's College Of Engineering. </option>
<option value="Syama Prasad College, Delhi.">Syama Prasad College, Delhi. </option>
<option value="Sydneham, Mumbai">Sydneham, Mumbai </option>
<option value="Syed Hasim College Of Science & Technology, Medak(AP).">Syed Hasim College Of Science & Technology, Medak(AP). </option>
<option value="Symbiosis Institute Of Business Management, Pune">Symbiosis Institute Of Business Management, Pune </option>
<option value="Symbiosis Institute Of International Business, Pune">Symbiosis Institute Of International Business, Pune </option>
<option value="Symbiosis, Pune.">Symbiosis, Pune. </option>
<option value="T,R,M.Campus Birgunj, Nepal.">T,R,M.Campus Birgunj, Nepal. </option>
<option value="T.I.E.T, Patiala.">T.I.E.T, Patiala. </option>
<option value="TAPMI, Manipal">TAPMI, Manipal </option>
<option value="Tata Institute Of Social Sciences, Mumbai">Tata Institute Of Social Sciences, Mumbai </option>
<option value="Techno India,salt Lake Kolkata.">Techno India,salt Lake Kolkata. </option>
<option value="Technocrats Institute Of Technology, Bhopal.">Technocrats Institute Of Technology, Bhopal. </option>
<option value="Thakral College Of Technology,Bhopal.">Thakral College Of Technology,Bhopal. </option>
<option value="Thakur Ram Multiple Campus, Birgunj(Nepal).">Thakur Ram Multiple Campus, Birgunj(Nepal). </option>
<option value="The Techno School,Bhubaneswar.">The Techno School,Bhubaneswar. </option>
<option value="Trident Academy Of Technology, Bhubaneswar.">Trident Academy Of Technology, Bhubaneswar. </option>
<option value="Trident Academy Of Technology,Bhubaneswar.">Trident Academy Of Technology,Bhubaneswar. </option>
<option value="Truba Institute Of Engineering And Information Technology, Bhopal.">Truba Institute Of Engineering And Information Technology, Bhopal. </option>
<option value="U.C.E, Burla.">U.C.E, Burla. </option>
<option value="UIET, Punjab University, Chandigarh.">UIET, Punjab University, Chandigarh. </option>
<option value="University Business School, Chandigarh">University Business School, Chandigarh </option>
<option value="University College Of Engineering, Visakhapatnam.">University College Of Engineering, Visakhapatnam. </option>
<option value="University Institute Of Technology(BU), Bhopal.">University Institute Of Technology(BU), Bhopal. </option>
<option value="University Visvesvaraya College Of Engineering, Bangalore.">University Visvesvaraya College Of Engineering, Bangalore. </option>
<option value="University, Chennai.">University, Chennai. </option>
<option value="Utkal University Departement Of Business Administration.">Utkal University Departement Of Business Administration. </option>
<option value="V.M.K.V. Engineering College, Salem.">V.M.K.V. Engineering College, Salem. </option>
<option value="VIT, Pune">VIT, Pune </option>
<option value="Vardhaman College Of Engineering, Ranga Reddy(AP).">Vardhaman College Of Engineering, Ranga Reddy(AP). </option>
<option value="Vasavi College Of Engineering, Hyderabad.">Vasavi College Of Engineering, Hyderabad. </option>
<option value="Vels Srinivasa College Of Engineering & Technology, Chennai.">Vels Srinivasa College Of Engineering & Technology, Chennai. </option>
<option value="Vidya Jyothi Institute Of Technology, Hyderabad.">Vidya Jyothi Institute Of Technology, Hyderabad. </option>
<option value="Vignan Engineering College, Guntur(AP).">Vignan Engineering College, Guntur(AP). </option>
<option value="Vishwakarma Institute Of Technology, Pune.">Vishwakarma Institute Of Technology, Pune. </option>
<option value="XLRI,Jamshedpur.">XLRI,Jamshedpur. </option>
<option value="Xavier Institute Of Management, Bhubaneshwar">Xavier Institute Of Management, Bhubaneshwar </option>
<option value="Xavier Institute Of Social Service,Ranchi.">Xavier Institute Of Social Service,Ranchi. </option>
<option value="Yashwantrao Chavan College Of Engineering (YCCE), Nagpur.">Yashwantrao Chavan College Of Engineering (YCCE), Nagpur. </option>
<option value="Zakir Husain College Of Engineering & Technology, AMU, Aligarh.">Zakir Husain College Of Engineering & Technology, AMU, Aligarh. </option>
<option value="nill">Others</option>